/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author William
 */
public class TelaPrincipal extends javax.swing.JFrame {
    public static int larg, comp;
     public static Login tela;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        jMenuBar1.setVisible(false);
        tela = new Login();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        
        setExtendedState(MAXIMIZED_BOTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmiCad_Contas = new javax.swing.JMenuItem();
        jmiCad_Usuarios = new javax.swing.JMenuItem();
        jmLancamentos = new javax.swing.JMenu();
        jmiVisualizar = new javax.swing.JMenuItem();
        jmRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA CONTROLE FINANCEIRO 1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jmCadastros.setText("Cadastros");
        jmCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrosActionPerformed(evt);
            }
        });

        jmiCad_Contas.setText("Cadastro de Conta");
        jmiCad_Contas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCad_ContasActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCad_Contas);

        jmiCad_Usuarios.setText("Cadastros de Usuários");
        jmiCad_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCad_UsuariosActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCad_Usuarios);

        jMenuBar1.add(jmCadastros);

        jmLancamentos.setText("Lançamentos");
        jmLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLancamentosActionPerformed(evt);
            }
        });

        jmiVisualizar.setText("Visualizar");
        jmiVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVisualizarActionPerformed(evt);
            }
        });
        jmLancamentos.add(jmiVisualizar);

        jMenuBar1.add(jmLancamentos);

        jmRelatorios.setText("Relatórios");
        jMenuBar1.add(jmRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(448, 394));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastrosActionPerformed

    private void jmiCad_ContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCad_ContasActionPerformed
        // TODO add your handling code here:
        CadastroConta tela = new CadastroConta();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jmiCad_ContasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println("Teste22 "+jDesktopPane1.getSize());
        larg = jDesktopPane1.getSize().width;
        comp  = jDesktopPane1.getSize().height;
        tela.central();
    }//GEN-LAST:event_formWindowOpened

    private void jmiCad_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCad_UsuariosActionPerformed
        // TODO add your handling code here:
        CadastroUsuario tela = new CadastroUsuario();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jmiCad_UsuariosActionPerformed

    private void jmLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLancamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmLancamentosActionPerformed

    private void jmiVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVisualizarActionPerformed
        // TODO add your handling code here:        
        Lancamentos tela = new Lancamentos();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jmiVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmLancamentos;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenuItem jmiCad_Contas;
    private javax.swing.JMenuItem jmiCad_Usuarios;
    private javax.swing.JMenuItem jmiVisualizar;
    // End of variables declaration//GEN-END:variables
}
